CREATE TABLE cms (
NPI TEXT,
NPPES_PROVIDER_LAST_ORG_NAME TEXT,
NPPES_PROVIDER_FIRST_NAME TEXT,
NPPES_PROVIDER_CITY TEXT,
NPPES_PROVIDER_STATE TEXT,
SPECIALTY_DESC TEXT,
DESCRIPTION_FLAG TEXT,
DRUG_NAME TEXT,
GENERIC_NAME TEXT,
BENE_COUNT INT,
TOTAL_CLAIM_COUNT INT,
TOTAL_DAY_SUPPLY INT,
TOTAL_DRUG_COST REAL,
BENE_COUNT_GE65 INT,
BENE_COUNT_GE65_REDACT_FLAT TEXT,
TOTAL_CLAIM_COUNT_GE65 INT,
GE65_REDACT_FLAG TEXT,
TOTAL_DAY_SUPPLY_GE65 INT,
TOTAL_DRUG_COST_GE65 REAL);

.separator \t
.import data/PARTD_PRESCRIBER_PUF_NPI_DRUG_13.tab cms

DELETE FROM cms WHERE NPI == 'NPI';
